### ISSUE TITLE
M_PI undeclared 

### ISSUE THREAD

**Issue by zjin-lcf** [AdamSimpson/SPH_Simple#2]
I cloned the project, and compile using the following command.  
Thanks.

cc -O3 -std=c99  src/fluid.c src/fileio.c src/geometry.c -o sph-cpu.out
src/fluid.c: In function ‘W’:
src/fluid.c:50:21: error: ‘M_PI’ undeclared (first use in this function)
     double C = 1.0/(M_PI*h*h*h);
                     ^
src/fluid.c:50:21: note: each undeclared identifier is reported only once for each function it appears in
src/fluid.c: In function ‘del_W’:
src/fluid.c:70:21: error: ‘M_PI’ undeclared (first use in this function)
     double C = 1.0/(M_PI * h*h*h);

**Comment by AdamSimpson** [comment]
You can define your own value if you'd like: `cc -DM_PI=3.14159265358979323846 ...`.
